# Generated by Django 5.0 on 2024-02-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', max_length=8),
        ),
    ]
