# Generated by Django 5.0 on 2024-02-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Refund', 'Refund'), ('Cancelled', 'Cancelled')], default='Paid', max_length=20),
        ),
    ]
