# Generated by Django 5.0 on 2024-02-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_promocode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
