# Generated by Django 5.0 on 2024-02-29 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_promocode_discount_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='apply_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
