# Generated by Django 5.0 on 2024-02-29 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_promocode_apply_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='time_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
